language: "pt-BR"
url: "https://callmarx.dev" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "CallMarx.dev" # the name of your site, e.g. ACME Corp.
name: "Eugenio Augusto Jimenes"
markdown: kramdown
highlighter: rouge
excerpt_separator: <!-- excerpt-end -->
word_count: 160

plugins:
  - jekyll-postcss
  - jekyll-archives
  - jekyll-paginate-v2

postcss:
  cache: false

tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - tags
  layout: archive
  permalinks:
    tag: '/tags/:name/'

pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"


defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - .gitignore
  - postcss.config.js
  - tailwind.config.js
