title: "CallMarx.dev"
tagline: "Desenvolvedor senior, disléxico e esquerdopata convicto"
description: "Blog/diário sobre minha relação de \"Credo, que delícia!\" com TI."
url: "https://callmarx.dev"
author: "Eugenio A. Jimenes"
image: "/assets/images/eu.webp"
language: "pt-BR"
baseurl: ""

google_analytics: G-M04ER887TV

twitter:
  username: callmarx_dev
  card: summary_large_image

facebook:
  app_id: 723752958736659

markdown: kramdown
highlighter: rouge
excerpt_separator: <!-- excerpt-end -->
word_count: 160

plugins:
  - jekyll-postcss
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

postcss:
  cache: false


pagination:
  enabled: true
  per_page: 4
  sort_reverse: true #for descending order by date
  permalink: "/page/:num/"
  trail:
    before: 2
    after: 2

autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts:
      - 'autopages_tags.html'
    title: ':tag' # :tag is replaced by the tag name
    permalink: '/tags/:tag'
    silent: false
    slugify:
      mode: 'default'   # :tag is slugified.
      case: false
    enabled: true

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post

include:
  - _pages
exclude:
  - .gitignore
  - .rubocop.yml
  - code_of_conduct.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - netlify.toml
  - node_modules
  - package-lock.json
  - package.json
  - postcss.config.js
  - README.md
  - tailwind.config.js
  - webpack.config.js
